version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    volumes:
      - ./:/app
  db:
    image: postgres:13
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  cache:
    image: redis:6.2
  
volumes:
  db-data: